// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activationCode.sql

package db

import (
	"context"
	"time"
)

const saveActivationCode = `-- name: SaveActivationCode :exec
INSERT INTO activation_codes (cadastro_id, code, expires_at)
VALUES ($1, $2, $3)
`

type SaveActivationCodeParams struct {
	CadastroID int64
	Code       string
	ExpiresAt  time.Time
}

func (q *Queries) SaveActivationCode(ctx context.Context, arg SaveActivationCodeParams) error {
	_, err := q.db.ExecContext(ctx, saveActivationCode, arg.CadastroID, arg.Code, arg.ExpiresAt)
	return err
}
