// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: activationCode.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getActivationCode = `-- name: GetActivationCode :one
SELECT a.id AS activation_id,
       a.cadastro_id,
       a.activation_codes,
       a.status AS code_status,
       c.status AS cadastro_status
FROM activation_code a
         JOIN cadastro c ON a.cadastro_id = c.id
WHERE a.activation_codes = $1
  AND a.cadastro_id = $2
`

type GetActivationCodeParams struct {
	ActivationCodes string
	CadastroID      int64
}

type GetActivationCodeRow struct {
	ActivationID    int32
	CadastroID      int64
	ActivationCodes string
	CodeStatus      sql.NullString
	CadastroStatus  string
}

func (q *Queries) GetActivationCode(ctx context.Context, arg GetActivationCodeParams) (GetActivationCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getActivationCode, arg.ActivationCodes, arg.CadastroID)
	var i GetActivationCodeRow
	err := row.Scan(
		&i.ActivationID,
		&i.CadastroID,
		&i.ActivationCodes,
		&i.CodeStatus,
		&i.CadastroStatus,
	)
	return i, err
}

const saveActivationCode = `-- name: SaveActivationCode :exec
INSERT INTO activation_code (cadastro_id, activation_codes, code, expires_at, status)
VALUES ($1, $2, $3, $4, $5)
`

type SaveActivationCodeParams struct {
	CadastroID      int64
	ActivationCodes string
	Code            string
	ExpiresAt       time.Time
	Status          sql.NullString
}

func (q *Queries) SaveActivationCode(ctx context.Context, arg SaveActivationCodeParams) error {
	_, err := q.db.ExecContext(ctx, saveActivationCode,
		arg.CadastroID,
		arg.ActivationCodes,
		arg.Code,
		arg.ExpiresAt,
		arg.Status,
	)
	return err
}
