// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cadastro.sql

package db

import (
	"context"
	"database/sql"
)

const createCadastro = `-- name: CreateCadastro :one
INSERT INTO cadastro (name, email, password, AcessID,created_at)
    VALUES ($1, $2, $3,$4,now())
RETURNING id, name, email, password, acessid, created_at
`

type CreateCadastroParams struct {
	Name     string
	Email    string
	Password string
	Acessid  sql.NullInt64
}

func (q *Queries) CreateCadastro(ctx context.Context, arg CreateCadastroParams) error {
	row := q.db.QueryRowContext(ctx, createCadastro,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Acessid,
	)
	var i Cadastro
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Acessid,
		&i.CreatedAt,
	)
	return err
}
