// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cadastro.sql

package db

import (
	"context"
	"database/sql"
)

const createCadastro = `-- name: CreateCadastro :one
INSERT INTO cadastro (name, cpf, cnpj, email, celular, password, status, activation_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, cpf, cnpj, email, celular, password, status, activation_code, created_at
`

type CreateCadastroParams struct {
	Name           string
	Cpf            sql.NullString
	Cnpj           sql.NullString
	Email          string
	Celular        string
	Password       string
	Status         string
	ActivationCode sql.NullString
}

func (q *Queries) CreateCadastro(ctx context.Context, arg CreateCadastroParams) (Cadastro, error) {
	row := q.db.QueryRowContext(ctx, createCadastro,
		arg.Name,
		arg.Cpf,
		arg.Cnpj,
		arg.Email,
		arg.Celular,
		arg.Password,
		arg.Status,
		arg.ActivationCode,
	)
	var i Cadastro
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cpf,
		&i.Cnpj,
		&i.Email,
		&i.Celular,
		&i.Password,
		&i.Status,
		&i.ActivationCode,
		&i.CreatedAt,
	)
	return i, err
}

const getCadastroByActivationCode = `-- name: GetCadastroByActivationCode :one
SELECT id, name, email, celular, status, activation_code
FROM cadastro
WHERE activation_code = $1 and id=$2
`

type GetCadastroByActivationCodeParams struct {
	ActivationCode sql.NullString
	ID             int64
}

type GetCadastroByActivationCodeRow struct {
	ID             int64
	Name           string
	Email          string
	Celular        string
	Status         string
	ActivationCode sql.NullString
}

func (q *Queries) GetCadastroByActivationCode(ctx context.Context, arg GetCadastroByActivationCodeParams) (GetCadastroByActivationCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getCadastroByActivationCode, arg.ActivationCode, arg.ID)
	var i GetCadastroByActivationCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Celular,
		&i.Status,
		&i.ActivationCode,
	)
	return i, err
}

const getSellerByCNPJ = `-- name: GetSellerByCNPJ :one
SELECT id, name, email, celular, password, status, activation_code, created_at
FROM cadastro
WHERE celular= $1
`

type GetSellerByCNPJRow struct {
	ID             int64
	Name           string
	Email          string
	Celular        string
	Password       string
	Status         string
	ActivationCode sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) GetSellerByCNPJ(ctx context.Context, celular string) (GetSellerByCNPJRow, error) {
	row := q.db.QueryRowContext(ctx, getSellerByCNPJ, celular)
	var i GetSellerByCNPJRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Celular,
		&i.Password,
		&i.Status,
		&i.ActivationCode,
		&i.CreatedAt,
	)
	return i, err
}

const updateCadastroStatus = `-- name: UpdateCadastroStatus :exec
UPDATE cadastro
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCadastroStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateCadastroStatus(ctx context.Context, arg UpdateCadastroStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCadastroStatus, arg.ID, arg.Status)
	return err
}
