// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: login.sql

package db

import (
	"context"
)

const createLogin = `-- name: CreateLogin :one
INSERT INTO login (email, password)
VALUES ($1, $2)
RETURNING email, password
`

type CreateLoginParams struct {
	Email    string
	Password string
}

func (q *Queries) CreateLogin(ctx context.Context, arg CreateLoginParams) (Login, error) {
	row := q.db.QueryRowContext(ctx, createLogin, arg.Email, arg.Password)
	var i Login
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const getLogin = `-- name: GetLogin :one
SELECT email, password
FROM login
WHERE email = $1
`

func (q *Queries) GetLogin(ctx context.Context, email string) (Login, error) {
	row := q.db.QueryRowContext(ctx, getLogin, email)
	var i Login
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}
