// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: login.sql

package db

import (
	"context"
	"database/sql"
)

const createLogin = `-- name: CreateLogin :one
INSERT INTO cadastro (email, password, activation_code, status)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password, activation_code, status, created_at
`

type CreateLoginParams struct {
	Email          string
	Password       string
	ActivationCode sql.NullString
	Status         string
}

type CreateLoginRow struct {
	ID             int64
	Email          string
	Password       string
	ActivationCode sql.NullString
	Status         string
	CreatedAt      sql.NullTime
}

func (q *Queries) CreateLogin(ctx context.Context, arg CreateLoginParams) (CreateLoginRow, error) {
	row := q.db.QueryRowContext(ctx, createLogin,
		arg.Email,
		arg.Password,
		arg.ActivationCode,
		arg.Status,
	)
	var i CreateLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.ActivationCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLogin = `-- name: GetLogin :one
SELECT email, password, activation_code,status
FROM cadastro
WHERE email = $1
`

type GetLoginRow struct {
	Email          string
	Password       string
	ActivationCode sql.NullString
	Status         string
}

func (q *Queries) GetLogin(ctx context.Context, email string) (GetLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getLogin, email)
	var i GetLoginRow
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.ActivationCode,
		&i.Status,
	)
	return i, err
}
