// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seller.sql

package db

import (
	"context"
	"database/sql"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO cadastro (
    activation_code,
    name,
    email,
    password,
    cpf,
    cnpj,
    celular,
    status,
    created_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8,NOW()
         )
RETURNING id, name, email, status,  activation_code, celular
`

type CreateSellerParams struct {
	ActivationCode sql.NullString
	Name           string
	Email          string
	Password       string
	Cpf            sql.NullString
	Cnpj           sql.NullString
	Celular        string
	Status         string
}

type CreateSellerRow struct {
	ID             int64
	Name           string
	Email          string
	Status         string
	ActivationCode sql.NullString
	Celular        string
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (CreateSellerRow, error) {
	row := q.db.QueryRowContext(ctx, createSeller,
		arg.ActivationCode,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Cpf,
		arg.Cnpj,
		arg.Celular,
		arg.Status,
	)
	var i CreateSellerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.ActivationCode,
		&i.Celular,
	)
	return i, err
}
