// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: seller.sql

package db

import (
	"context"
	"database/sql"
)

const createSeller = `-- name: CreateSeller :one
INSERT INTO cadastro (
    name,
    email,
                      activation_code,
    password,
    cpf,
    cnpj,
    celular,
    status,
    created_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7,$8, NOW()
         )
RETURNING id AS cadastro_id,activation_code, status
`

type CreateSellerParams struct {
	Name           string
	Email          string
	ActivationCode sql.NullString
	Password       string
	Cpf            sql.NullString
	Cnpj           sql.NullString
	Celular        string
	Status         string
}

type CreateSellerRow struct {
	CadastroID     int64
	ActivationCode sql.NullString
	Status         string
}

func (q *Queries) CreateSeller(ctx context.Context, arg CreateSellerParams) (CreateSellerRow, error) {
	row := q.db.QueryRowContext(ctx, createSeller,
		arg.Name,
		arg.Email,
		arg.ActivationCode,
		arg.Password,
		arg.Cpf,
		arg.Cnpj,
		arg.Celular,
		arg.Status,
	)
	var i CreateSellerRow
	err := row.Scan(&i.CadastroID, &i.ActivationCode, &i.Status)
	return i, err
}
